### ISSUE TITLE
suggest: deefault action when playback error

### ISSUE THREAD

**Issue by xeonds** [Reverier-Xu/BitWave#10]
## Description

When play an item **failed**, just **stop playing instead of going to the next item**

## Reason

Assuming a list with most items not exist(like moved to other location), when user click on an item, the bitwave will **loop under current playback settings, like loop down/up/random until it finds a playable song/reach the border of list**.

The above action will take high cpu usage, and in some case, **user can't stop the play process**.

**Comment by Reverier-Xu** [comment]
maybe we can add a `faillock`-like things here.

**Comment by Reverier-Xu** [comment]
seems the implementation have some bugs, reopen this issue until I fix that.

**Comment by Reverier-Xu** [comment]
fixed at [releases/tag/v1.1.1](https://github.com/Reverier-Xu/BitWave/releases/tag/v1.1.1)
